# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Upload files via FTP
    - name: 'File upload'
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: 'ftp://ftp.artisana.ng'
        # FTP user
        user: 'artisan3'
        # FTP password
        password: '7q3rWX[(NjcP16'
        # Force SSL encryption
        # forceSsl: # optional, default is false
        # Local directory
        localDir: './' # optional, default is .
        # Remote directory
        remoteDir: 'demo' # optional, default is .
